import Link from "next/link";
import { headers } from "next/headers";
import { redirect } from "next/navigation";
import { currentMember, getCard } from "@/shared/members";
import { logOut } from "@/features/membership/actions";
import { formatVisit } from "@/shared/format";
import { Footer } from "@/shared/ui/footer";
import { Progress } from "@/shared/ui/progress";
import { Slots } from "@/shared/ui/slots";
import { RefreshButton } from "@/features/membership/refresh-button";
import { memberScanUrl, qrSvg } from "@/shared/qr";

export const dynamic = "force-dynamic";

export default async function CardPage({
  searchParams,
}: {
  searchParams: Promise<{ welcome?: string }>;
}) {
  const member = await currentMember();
  if (!member) redirect("/");

  const card = await getCard(member.id);
  const { welcome } = await searchParams;
  const firstName = member.name.split(" ")[0];

  // x-forwarded-proto rather than a hardcoded https, so the code still points
  // somewhere reachable when this runs over plain http in local development.
  const head = await headers();
  const scanSvg = await qrSvg(
    memberScanUrl(
      head.get("host") ?? "",
      head.get("x-forwarded-proto") ?? "http",
      member.id,
    ),
  );

  return (
    <div className="shell">
      <main className="screen">
        <p className="eyebrow">
          {welcome ? `Welcome, ${firstName}` : "Getta Rewards"}
        </p>

        {welcome ? (
          <p className="sub">
            Your card is open and waiting for its first stamp. Show the code
            below at the counter on your next visit.
          </p>
        ) : null}

        <div className="member">
          <p className="name">{member.name}</p>
          <span className="since">{member.phone}</span>
        </div>

        <div className="stampcard">
          <Slots stamps={card.stamps} />
          <Progress stamps={card.stamps} redeemed={card.redeemed} />
        </div>

        <div className="qrblock">
          {/* The SVG is generated by qrcode from a URL this server built, not
              from anything the member typed. aria-hidden because the code is a
              picture of the line of text below it. */}
          <div
            className="qr"
            aria-hidden="true"
            dangerouslySetInnerHTML={{ __html: scanSvg }}
          />
          <p className="qrnote">Show this at the counter to collect a stamp</p>
        </div>

        {card.rewardsReady > 0 ? (
          <div className="stack">
            <Link className="btn gold" href="/card/reward">
              {card.rewardsReady > 1
                ? `VIEW MY ${card.rewardsReady} FREE DRINKS`
                : "VIEW MY FREE DRINK"}
            </Link>
          </div>
        ) : null}

        <div className="hist">
          <h2>Visit history</h2>
          {card.visits.length === 0 && card.redeemed === 0 ? (
            <p className="none">
              No visits yet. Your first stamp lands the next time you order.
            </p>
          ) : (
            <ul>
              {card.visits.map((visit) => (
                <li key={visit.at}>
                  <span>
                    Receipt collected
                    {visit.location ? ` · ${visit.location}` : ""}
                  </span>
                  <span>{formatVisit(visit.at)}</span>
                </li>
              ))}
              {card.redeemed > 0 ? (
                <li>
                  <span>Free drink redeemed</span>
                  <span>{card.redeemed}× to date</span>
                </li>
              ) : null}
            </ul>
          )}
        </div>

        <div className="stack">
          <RefreshButton />
        </div>

        <form action={logOut} className="signout">
          <button className="link" type="submit">
            Sign out
          </button>
        </form>

        <Footer />
      </main>
    </div>
  );
}

export const metadata = { title: "My Card · Getta Rewards" };
