import Link from "next/link";
import { headers } from "next/headers";
import { redirect } from "next/navigation";
import { loadCard } from "@/shared/members";
import { currentMemberId } from "@/shared/session";
import { logOut } from "@/features/membership/actions";
import { Footer } from "@/shared/ui/footer";
import { Wordmark } from "@/shared/ui/wordmark";
import { Progress } from "@/shared/ui/progress";
import { Slots } from "@/shared/ui/slots";
import { RefreshButton } from "@/features/membership/refresh-button";
import { memberScanUrl, qrSvg } from "@/shared/qr";
import { InstallHint } from "@/features/pwa/install-hint";

export const dynamic = "force-dynamic";

export default async function CardPage({
  searchParams,
}: {
  searchParams: Promise<{ welcome?: string }>;
}) {
  // The cookie names a member; the row proves one. Resolved together with the
  // card so the whole screen costs a single round trip.
  const id = await currentMemberId();
  const found = id ? await loadCard(id) : null;
  if (!found) redirect("/");
  const { member, card } = found;

  const { welcome } = await searchParams;
  const firstName = member.name.split(" ")[0];

  // x-forwarded-proto rather than a hardcoded https, so the code still points
  // somewhere reachable when this runs over plain http in local development.
  const head = await headers();
  const scanSvg = await qrSvg(
    memberScanUrl(
      head.get("host") ?? "",
      head.get("x-forwarded-proto") ?? "http",
      member.id,
    ),
  );

  return (
    <div className="shell">
      <main className="screen">
        <Wordmark />

        {/* The eyebrow now carries only the greeting. A returning member gets
            the mark and nothing else above their name; the label that used to
            sit here said what the logo says. */}
        {welcome ? <p className="eyebrow">Welcome, {firstName}</p> : null}

        {welcome ? (
          <p className="sub">
            Your card is open and waiting for its first stamp. Show the code
            below at the counter on your next visit.
          </p>
        ) : null}

        <div className="member">
          <p className="name">{member.name}</p>
        </div>

        <div className="stampcard">
          <Slots stamps={card.stamps} />
          <Progress stamps={card.stamps} redeemed={card.redeemed} />
        </div>

        <div className="qrblock">
          {/* The SVG is generated by qrcode from a URL this server built, not
              from anything the member typed. aria-hidden because the code is a
              picture of the line of text below it. */}
          <div
            className="qr"
            aria-hidden="true"
            dangerouslySetInnerHTML={{ __html: scanSvg }}
          />
          <p className="qrnote">Show this at the counter to collect a stamp</p>
        </div>

        {/* Directly under the code, where its value is obvious: the thing you
            hold up at the counter is worth one tap away, not three. */}
        <InstallHint storageKey="getta-install-card" />

        {card.rewardsReady > 0 ? (
          <div className="stack">
            <Link className="btn gold" href="/card/reward">
              {card.rewardsReady > 1
                ? `VIEW MY ${card.rewardsReady} FREE DRINKS`
                : "VIEW MY FREE DRINK"}
            </Link>
          </div>
        ) : null}

        <div className="stack">
          <Link className="btn ghost" href="/card/leaderboard">
            LEADERBOARD
          </Link>
          <RefreshButton />
        </div>

        <form action={logOut} className="signout">
          <button className="link" type="submit">
            Sign out
          </button>
        </form>

        <Footer />
      </main>
    </div>
  );
}

export const metadata = { title: "My Card · Getta Rewards" };
